.github/workflows/frontend.yml
CI/CD 파이프라인 등록
1. add frontend.yml
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> [CD] create frontend.yml

.github/workflows/frontend-dev.yml
dev랑 production 서버 나눠서 프론트 배포가능
1. production 서버 경로추가
2. Dev 파일 추가
1. [테스트 1]
3. [테스트 2]
4. [테스트 3]
=> [FEAT] dev랑 production 나눠서 CI/CD

src/components/CategoryModal.tsx, src/components/FilterModal.tsx, src/components/ToastMessage.tsx, src/pages/Detail.tsx, src/pages/Login.tsx, src/pages/Main.tsx, src/pages/Profile.tsx, src/pages/Search.tsx
- Resolves #23 
1. 전체 페이지 규격
2. 모달창 규격격
3. 토스트 메시지 규격
1. MacOS Chrome
=> fix: 화면 비율 변경

.github/workflows/frontend.yml
update frontend.yml
1. frontend.yml 파일 수정
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> FIX(cd): update frontend.yml

.github/workflows/frontend-dev.yml
update frontedn-dev.yml
1. frontend-dev.yml 파일 수정
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> Fix(cd): update frontend-dev.yml

.github/workflows/frontend.yml
frontend.yml 파일 수정
1. frontend.yml 파일 수정
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix(cd): 제발 되게 해주세요

src/pages/Detail.tsx, src/pages/Main.tsx
- Resolves #34 
1. 상세페이지 왼쪽 정렬
2. 메인 페이지 썸네일 화살표 가운데
1. MacOS
=> fix: 메인 페이지 css

src/App.tsx, src/api/config.ts, src/components/CategoryModal.tsx, src/components/FilterModal.tsx, src/components/PriceTab.tsx, src/pages/Detail.tsx, src/pages/Login.tsx, src/pages/Main.tsx, src/pages/Profile.tsx, src/pages/Search.tsx, src/services/categoryService.ts, src/services/gameService.ts, src/services/searchService.ts, src/services/userService.ts
- Resolves #38 
1. 역대 최저가 더미 데이터가 아닌 실제 데이터 사용 + UI 디자인 개선
2. 검색 페이지 할인 탭
3. 상세 페이지 할인하지않은 게임은 가격 표시 없애기
4. 카테고리 버튼 오류 수정
1. MacOS
=> fix: solved issue #38

src/components/RangeSlider.tsx, src/pages/Profile.tsx
- Resolves eslint warnings
1. fixed eslint warning 
1. MacOS Chrome
=> fix: eslint warning RangeSlider.tsx

src/pages/Search.tsx
- Resolves Eslint warning
1. Search.tsx: edited dependency arrays
1. MacOS
=> fix: eslint warning Search.tsx

src/components/PartyFindTab.tsx, src/pages/Profile.tsx
- Resolves [#6](https://github.com/100-hours-a-week/9-team-gudokjohayo-warab-wiki/issues/6#issue-2958710878)
1. maxlength = 100 조정
1. macOS
=> fix: comment max length

src/pages/Profile.tsx
1. 
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: issues from wiki

src/components/FilterModal.tsx, src/services/searchService.ts
- Resolves [#11](https://github.com/100-hours-a-week/9-team-gudokjohayo-warab-wiki/issues/11#issue-2958719449)
- Resolves [#21](https://github.com/100-hours-a-week/9-team-gudokjohayo-warab-wiki/issues/21#issue-2959718206)
1. 필터 ui 변경
1. macOS
=> fix: filter issues from wiki

src/pages/info.tsx
서비스 설명 페이지 추가 
1. 로그인 시 진입하는 설명 페이지 추가 
2. 프로필 페이지와 연결
=> feat: 서비스 설명 페이지 추가

src/App.tsx
=> feat: info 페이지 엔드포인트 추가

src/components/PartyFindTab.tsx
- Resolves warnings
1. removed unused variables
1. macOS
=> fix: removed unused variable

src/pages/Login.tsx, src/pages/Main.tsx, src/pages/Profile.tsx, src/pages/Search.tsx, src/services/searchService.ts, src/services/userService.ts
1. [#46](https://github.com/100-hours-a-week/9-team-gudokjohayo-warab-wiki/issues/46#issue-2965471413) 검색할때 리로드되며 깜빡이는 현상
2. [#51](https://github.com/100-hours-a-week/9-team-gudokjohayo-warab-wiki/issues/51#issue-2965496223) 닉네임 ₩로 설정가능
3. [#58](https://github.com/100-hours-a-week/9-team-gudokjohayo-warab-wiki/issues/58#issue-2965540469) 뒤로가기 버튼 동작 안함
1. macOS
=> fix: issue 46,51,58 from wiki repo

src/components/PartyFindTab.tsx
1. [#57](https://github.com/100-hours-a-week/9-team-gudokjohayo-warab-wiki/issues/57#issue-2965525299) 댓글 두번 등록 현상 제거
2. [#65](https://github.com/100-hours-a-week/9-team-gudokjohayo-warab-wiki/issues/65#issue-2965630135) 댓글 정렬 추가
3. [#62](https://github.com/100-hours-a-week/9-team-gudokjohayo-warab-wiki/issues/62#issue-2965580602) 댓글 화면 벗어나는 현상 제거
1. macOS
=> fix: issue 57(댓글 두번 입력 현상), 65(댓글 정렬), 62(댓글 화면 벗어남)

src/components/PartyFindTab.tsx
=> feat: 비회원 댓글 제한

src/services/searchService.ts
1. commented unused function
1. macOS
=> fix: removed never used

src/App.tsx, src/api/usePageTracking.ts, src/components/TrackingWrapper.tsx
1. created TrackingWrapper component
1. macOS
=> fix: create TrackingWrapper component

src/components/PartyFindTab.tsx, src/services/commentService.ts
1. comment api removed discord_url
1. macos
=> fix: comment removed discord_url from api

src/App.tsx, src/components/AddServerModal.tsx, src/components/PartyRegistration.tsx, src/components/PriceTab.tsx, src/index.tsx, src/pages/Detail.tsx, src/pages/Login.tsx, src/pages/Main.tsx, src/pages/Profile.tsx, src/pages/Search.tsx, src/sentry/ErrorBoundary.tsx, src/sentry/errorHandler.ts, src/sentry/sentry.ts
1. sentry 세팅
2. 0월 → 무료로 표시
3. 최저가 플랫폼 최저가부터 정렬
4. 디스코드 서버 등록 예외처리 문구 추가
5. 만료된 서버의 경우 파치등록탭에서 숨김표시 
1. macOS
=> Feature/sentry + 기능 개선

src/components/PriceTab.tsx
1. 상세페이지 가격 비교 무료라고 뜨는 오류 수정
1. macOS
=> fix: 상세페이지 가격 비교 무료라고 뜨는 오류 수정
